apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: gurtech-co-uk-tls
spec:
    secretName: gurtech-co-uk
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: gurtech.co.uk
    dnsNames:
        - gurtech.co.uk
        - www.gurtech.co.uk
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - gurtech.co.uk
                - www.gurtech.co.uk